version: '3.9'

volumes:
  postgres_data_coffeo:

services:
  backend_coffeo:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - postgres_coffeo
    volumes:
      - ./:/app
    command: >
      sh -c "pip install -r requirements.txt && python3 manage.py migrate && python3 manage.py collectstatic --noinput && gunicorn --timeout 20 --bind 0.0.0.0:8000 project.wsgi:application --workers=3 --threads=2 --worker-class=gthread
      "
    restart: always
    env_file: .env
    ports:
      - 8000:8000

  postgres_coffeo:
    image: postgres:12.6
    volumes:
      - postgres_data_coffeo:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 37222:5432
