# Generated by Django 5.0.6 on 2024-07-29 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=264, unique=True)),
                ("price", models.FloatField(null=True)),
                ("category", models.CharField(max_length=264)),
                ("subcategory", models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount", models.FloatField(null=True)),
                ("end_date", models.DateTimeField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="api.product",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Accessories",
        ),
        migrations.DeleteModel(
            name="Apparel",
        ),
        migrations.DeleteModel(
            name="CoffeeBeans",
        ),
    ]
