services:
  coffeo_service_base:
    build:
      context: ../../../
      dockerfile: deployments/backend/coffeo/Dockerfile
    restart: always
    networks:
      - local_backend_network
      - local_coffeo_network
    environment:
      - LOCAL_RUN=True
      - DEBUG=${LOCAL_COFFEO_PANEL_DEBUG}
      - SECRET_KEY=${LOCAL_COFFEO_PANEL_SECRET_KEY}
      - ALLOWED_HOSTS=${LOCAL_COFFEO_PANEL_ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${LOCAL_COFFEO_PANEL_CSRF_TRUSTED_ORIGINS}
      - CORS_ALLOWED_ORIGINS=${LOCAL_COFFEO_PANEL_CORS_ALLOWED_ORIGINS}
      - ADMIN_GRPC_PORT=${LOCAL_COFFEO_GRPC_PORT}
      - DB_NAME=${LOCAL_COFFEO_DB_NAME}
      - DB_USER=${LOCAL_COFFEO_DB_USER}
      - DB_PASSWORD=${LOCAL_COFFEO_DB_PASSWORD}
      - DB_PORT=${LOCAL_COFFEO_DB_PORT}
      - DB_HOST=${LOCAL_COFFEO_DB_HOST}
      - AWS_ACCESS_KEY_ID=${LOCAL_COFFEO_PANEL_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${LOCAL_COFFEO_PANEL_AWS_SECRET_ACCESS_KEY}
      - AWS_S3_ENDPOINT_URL=${LOCAL_COFFEO_PANEL_AWS_S3_ENDPOINT_URL}
      - AWS_S3_BUCKET_NAME=${LOCAL_COFFEO_PANEL_AWS_S3_BUCKET_NAME}
      - REDIS_HOST=${LOCAL_COFFEO_REDIS_HOST}
      - REDIS_PORT=${LOCAL_COFFEO_REDIS_PORT}
      - REDIS_PASSWORD=${LOCAL_COFFEO_REDIS_PASSWORD}
      - AUTH_GRPC_HOST=${LOCAL_AUTH_GRPC_HOST}
      - AUTH_GRPC_PORT=${LOCAL_AUTH_GRPC_PORT}
      - TINKOFF_TERMINAL_KEY=${LOCAL_COFFEO_TINKOFF_TERMINAL_KEY}
      - TINKOFF_PASSWORD=${LOCAL_COFFEO_TINKOFF_PASSWORD}
      - TINKOFF_LIFETIME_LINK_MUNUTES=${LOCAL_COFFEO_TINKOFF_LIFETIME_LINK_MUNUTES}
      - TINKOFF_NOTIFICATION_URL=${LOCAL_COFFEO_TINKOFF_NOTIFICATION_URL}
      - TOCHKA_ACCESS_KEY=${LOCAL_COFFEO_TOCHKA_ACCESS_KEY}
      - TOCHKA_CUSTOMER_CODE=${LOCAL_COFFEO_TOCHKA_CUSTOMER_CODE}
      - SENTRY_DSN=${LOCAL_COFFEO_SENTRY_DSN}
      - SENTRY_TRACES_SAMPLE_RATE=${LOCAL_COFFEO_SENTRY_TRACES_SAMPLE_RATE}
      - SENTRY_PROFILES_SAMPLE_RATE=${LOCAL_COFFEO_SENTRY_PROFILES_SAMPLE_RATE}
      - DOMAIN=${LOCAL_COFFEO_DOMAIN}
      - HTTP_PROTOCOL=${LOCAL_COFFEO_HTTP_PROTOCOL}

      - EMAIL_HOST=${LOCAL_EMAIL_HOST}
      - EMAIL_HOST_TLS=${LOCAL_EMAIL_HOST_TLS}
      - EMAIL_USE_SSL=${LOCAL_EMAIL_USE_SSL}
      - EMAIL_HOST_PORT=${LOCAL_EMAIL_HOST_PORT}
      - EMAIL_HOST_USER=${LOCAL_EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${LOCAL_EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${LOCAL_DEFAULT_FROM_EMAIL}
      - EMAIL_ADMIN=${LOCAL_COFFEO_EMAIL}
